### ISSUE TITLE
error when running Python bindings example

### ISSUE THREAD

**Issue by nibrunie** [llvm/circt#3500]
Using a clone from 53a60c651c6f235d628a8fc6b1ceec0a3d94319b
After installing the python bindings through a `pip install .` in `lib/Bindins/Python`, I tried the example from https://circt.llvm.org/docs/PythonBindings/#trying-things-out and got the following error:

```
$  python3 silicon.py 
Traceback (most recent call last):
  File "silicon.py", line 14, in <module>
    hw.HWModuleOp(name="magic", body_builder=magic)
  File "/media/nicolas/cecb8df5-3fa0-471c-ac32-67d64ccdb31e/home/nicolas/circt/build/circt_venv/lib/python3.8/site-packages/circt/dialects/_hw_ops_ext.py", line 300, in __init__
    super().__init__(name,
  File "/media/nicolas/cecb8df5-3fa0-471c-ac32-67d64ccdb31e/home/nicolas/circt/build/circt_venv/lib/python3.8/site-packages/circt/dialects/_hw_ops_ext.py", line 179, in __init__
    outputs = body_builder(self)
TypeError: magic() missing 1 required positional argument: 'b'
```

Is something wrong with my setup ?

**Comment by mikeurbach** [comment]
Seems the example was just out of date, should be fixed by https://github.com/llvm/circt/commit/5d8abac0f503148b0a68a7c8c801acf7a4715907.
