### ISSUE TITLE
[pycde] FSM error

### ISSUE THREAD

**Issue by Dragon-Git** [llvm/circt#5488]
FSM produces the following error:
```
Traceback (most recent call last):
  File "F:\project\pycde_example\fsm.py", line 5, in <module>
    @fsm.machine()
     ^^^^^^^^^^^^^
  File "C:\Users\uname\project\env\pycde_example\Lib\site-packages\pycde\fsm.py", line 191, in machine_clocked
    fsm_mod = module(to_be_wrapped)
              ^^^^^^
NameError: name 'module' is not defined. Did you mean: 'Module'?

```

OS: Window 10
pycde version: 0.2.1.dev823
The python code is:

```python
from pycde import (Output, Input, Module, generator, types, dim, System)
from pycde import fsm

@fsm.machine()
class FSM:
  a = Input(types.i1)
  b = Input(types.i1)
  c = Input(types.i1)

  # States
  A = fsm.State(initial=True)
  (B, C) = fsm.States(2)

  # Transitions
  A.set_transitions((B, lambda ports: ports.a))
  B.set_transitions((A, lambda ports: ports.b), (C,))
  C.set_transitions((B, lambda ports: ports.a))

mod = System([FSM],name="fsm_test")
mod.compile()

```

**Comment by teqdruid** [comment]
@Dragon-Git FSMs should work again, with slightly different syntax: https://github.com/llvm/circt/blob/d7108532ce9f46d37cceb698f11ed0cd7c1e5a3f/frontends/PyCDE/test/test_fsm.py#L78 This is the new way of creating and extending "module like" constructs.
