### ISSUE TITLE
[FIRRTL] ASAN error with Intrinsic framework's string handling

### ISSUE THREAD

**Issue by dtzSiFive** [llvm/circt#6533]
Errors like this:
```
RUN: at line 1: /build/sifive/asan/bin/firtool --ir-hw /home/will/src/sifive/circt/test/firtool/has_been_reset.fir | /build/sifive/asan/bin/FileCheck /home/will/src/sifive/circt/test/firtool/has_been_reset.fir
+ /build/sifive/asan/bin/firtool --ir-hw /home/will/src/sifive/circt/test/firtool/has_been_reset.fir
+ /build/sifive/asan/bin/FileCheck /home/will/src/sifive/circt/test/firtool/has_been_reset.fir
=================================================================
==3953477==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f68009dd248 at pc 0x5628c213e285 bp 0x7ffdd4b22050 sp 0x7ffdd4b22048
READ of size 8 at 0x7f68009dd248 thread T0
    #0 0x5628c213e284 in void circt::firrtl::IntrinsicLowerings::addConverter<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::DenseMap<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>, llvm::DenseMapInfo<mlir::StringAttr, void>, llvm::detail::DenseMapPair<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>>>&, llvm::StringRef)::'lambda'(circt::firrtl::FModuleLike)::operator()(circt::firrtl::FModuleLike) const /home/
will/src/sifive/circt/include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.h:135:14
    #1 0x5628c213e284 in mlir::LogicalResult std::__invoke_impl<mlir::LogicalResult, void circt::firrtl::IntrinsicLowerings::addConverter<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::DenseMap<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>, llvm::DenseMapInfo<mlir::StringAttr, void>, llvm::detail::DenseMapPair<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>>>&, llvm::StringRef)::'lambda'(circt::firrtl::FModu
leLike)&, circt::firrtl::FModuleLike>(std::__invoke_other, void circt::firrtl::IntrinsicLowerings::addConverter<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::DenseMap<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>, llvm::DenseMapInfo<mlir::StringAttr, void>, llvm::detail::DenseMapPair<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>>>&, llvm::StringRef)::'lambda'(circt::firrtl::FModuleLike)&, circt::firrtl::F
ModuleLike&&) /nix/store/1x1q5sqa0ilbi8fz7aayk02pjy5g7jhh-gcc-12.3.0/include/c++/12.3.0/bits/invoke.h:61:14
    #2 0x5628c213e284 in std::enable_if<is_invocable_r_v<mlir::LogicalResult, void circt::firrtl::IntrinsicLowerings::addConverter<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::DenseMap<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>, llvm::DenseMapInfo<mlir::StringAttr, void>, llvm::detail::DenseMapPair<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>>>&, llvm::StringRef)::'lambda'(circt::firrtl::FModuleLike)
&, circt::firrtl::FModuleLike>, mlir::LogicalResult>::type std::__invoke_r<mlir::LogicalResult, void circt::firrtl::IntrinsicLowerings::addConverter<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::DenseMap<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>, llvm::DenseMapInfo<mlir::StringAttr, void>, llvm::detail::DenseMapPair<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>>>&, llvm::StringRef)::'lambda'(circt::fi
rrtl::FModuleLike)&, circt::firrtl::FModuleLike>(void circt::firrtl::IntrinsicLowerings::addConverter<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::DenseMap<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>, llvm::DenseMapInfo<mlir::StringAttr, void>, llvm::detail::DenseMapPair<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>>>&, llvm::StringRef)::'lambda'(circt::firrtl::FModuleLike)&, circt::firrtl::FModuleLike
&&) /nix/store/1x1q5sqa0ilbi8fz7aayk02pjy5g7jhh-gcc-12.3.0/include/c++/12.3.0/bits/invoke.h:114:9
    #3 0x5628c213e284 in std::_Function_handler<mlir::LogicalResult (circt::firrtl::FModuleLike), void circt::firrtl::IntrinsicLowerings::addConverter<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::DenseMap<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>, llvm::DenseMapInfo<mlir::StringAttr, void>, llvm::detail::DenseMapPair<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>>>&, llvm::StringRef)::'lambda'(circt::
firrtl::FModuleLike)>::_M_invoke(std::_Any_data const&, circt::firrtl::FModuleLike&&) /nix/store/1x1q5sqa0ilbi8fz7aayk02pjy5g7jhh-gcc-12.3.0/include/c++/12.3.0/bits/std_function.h:290:9
    #4 0x5628c2ee7225 in std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>::operator()(circt::firrtl::FModuleLike) const /nix/store/1x1q5sqa0ilbi8fz7aayk02pjy5g7jhh-gcc-12.3.0/include/c++/12.3.0/bits/std_function.h:591:9
    #5 0x5628c2ee7225 in circt::firrtl::IntrinsicLowerings::lower(circt::firrtl::CircuitOp) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp:157:16
    #6 0x5628c2129aac in (anonymous namespace)::LowerIntrinsicsPass::runOnOperation() /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp:552:23
    #7 0x5628c3fa8afc in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_1::operator()() const /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:503:17
    #8 0x5628c3fa8afc in void llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_1>(long) /home/will/src/sifive/circt/llvm/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
    #9 0x5628c3f9c8bb in llvm::function_ref<void ()>::operator()() const /home/will/src/sifive/circt/llvm/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #10 0x5628c3f9c8bb in void mlir::MLIRContext::executeAction<mlir::PassExecutionAction, mlir::Pass&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, mlir::Pass&) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/MLIRContext.h:275:7
    #11 0x5628c3f9c8bb in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:497:21
    #12 0x5628c3f9e2b5 in mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:569:16
    #13 0x5628c3fa9dea in mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_0::operator()(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&) const /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:789:36
    #14 0x5628c3fa1572 in mlir::LogicalResult mlir::failableParallelForEach<__gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>>, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_0&>(mlir::MLIRContext*, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>>, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>>, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_0&) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/Threading.h:46:18
    #15 0x5628c3fa1572 in mlir::LogicalResult mlir::failableParallelForEach<std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>&, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_0&>(mlir::MLIRContext*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo>>&, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_0&) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/Threading.h:92:10
    #16 0x5628c3fa1572 in mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:799:14
    #17 0x5628c3fa8b6b in mlir::detail::OpToOpPassAdaptor::runOnOperation(bool) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:690:5
    #18 0x5628c3fa8b6b in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_1::operator()() const /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:501:20
    #19 0x5628c3fa8b6b in void llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_1>(long) /home/will/src/sifive/circt/llvm/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
    #20 0x5628c3f9c8bb in llvm::function_ref<void ()>::operator()() const /home/will/src/sifive/circt/llvm/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #21 0x5628c3f9c8bb in void mlir::MLIRContext::executeAction<mlir::PassExecutionAction, mlir::Pass&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, mlir::Pass&) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/MLIRContext.h:275:7
    #22 0x5628c3f9c8bb in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:497:21
    #23 0x5628c3f9e2b5 in mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:569:16
    #24 0x5628c3fa4536 in mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:880:10
    #25 0x5628c3fa4536 in mlir::PassManager::run(mlir::Operation*) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:860:60
    #26 0x5628c189804e in processBuffer(mlir::MLIRContext&, circt::firtool::FirtoolOptions&, mlir::TimingScope&, llvm::SourceMgr&, std::optional<std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>>&) /home/will/src/sifive/circt/tools/firtool/firtool.cpp:464:17
    #27 0x5628c1895fea in processInputSplit(mlir::MLIRContext&, circt::firtool::FirtoolOptions&, mlir::TimingScope&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, std::optional<std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>>&) /home/will/src/sifive/circt/tools/firtool/firtool.cpp:536:12
    #28 0x5628c189495e in processInput(mlir::MLIRContext&, circt::firtool::FirtoolOptions&, mlir::TimingScope&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, std::optional<std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>>&) /home/will/src/sifive/circt/tools/firtool/firtool.cpp:552:12
    #29 0x5628c189495e in executeFirtool(mlir::MLIRContext&, circt::firtool::FirtoolOptions&) /home/will/src/sifive/circt/tools/firtool/firtool.cpp:643:14
    #30 0x5628c1893cd5 in main /home/will/src/sifive/circt/tools/firtool/firtool.cpp:727:17
    #31 0x7f6802712acd in __libc_start_call_main (/nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8/lib/libc.so.6+0x23acd) (BuildId: 344aaad51978b8c259311fba5dc7581f830bad5a)
    #32 0x7f6802712b88 in __libc_start_main@GLIBC_2.2.5 (/nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8/lib/libc.so.6+0x23b88) (BuildId: 344aaad51978b8c259311fba5dc7581f830bad5a)
    #33 0x5628c1763344 in _start (/build/sifive/asan/bin/firtool+0x1af9344)

Address 0x7f68009dd248 is located in stack of thread T0 at offset 72 in frame
    #0 0x5628c213db2f in void circt::firrtl::IntrinsicLowerings::add<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::StringRef) /home/will/src/sifive/circt/include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.h:107

  This frame has 4 object(s):
    [32, 40) 'ConstFoundBucket.i.i.i'
    [64, 80) 'name.i' (line 138) <== Memory access at offset 72 is inside this variable
    [96, 104) 'nameAttr.i' (line 133)
    [128, 168) 'ref.tmp.i' (line 133)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-return /home/will/src/sifive/circt/include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.h:135:14 in void circt::firrtl::IntrinsicLowerings::addConverter<(anonymous namespace)::CirctHasBeenResetConverter>(llvm::DenseMap<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>, llvm::DenseMapInfo<mlir::StringAttr, void>, llvm::detail::DenseMapPair<mlir::StringAttr, std::function<mlir::LogicalResult (circt::firrtl::FModuleLike)>>>&, llvm::StringRef)::'lambda'(circt::firrtl::FModuleLike)::operator()(circt::firrtl::FModuleLike) const
Shadow bytes around the buggy address:
  0x7f68009dcf80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f68009dd000: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f68009dd080: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f68009dd100: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f68009dd180: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x7f68009dd200: f5 f5 f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5
  0x7f68009dd280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f68009dd300: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f68009dd380: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f68009dd400: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f68009dd480: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3953477==ABORTING
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /build/sifive/asan/bin/FileCheck /home/will/src/sifive/circt/test/firtool/has_been_reset.fir
```

I think the "name" StringRef captured by the lambda can go out of scope (even if the string it points to is contractually expected to outlive all this?), which looks to match the error.

**Comment by dtzSiFive** [comment]
Reverting #6527 fixes the error.

Actually I'll take a look at fixing this...
